--- 
chdir: /sites/ninja/current/
environment: production
address: 0.0.0.0
port: 3000
timeout: 30
log: /sites/ninja/shared/log/thin.log
pid: /sites/ninja/shared/tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 30
servers: 1
daemonize: true